name: toga
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7878559716045856
title: toga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1641908180899918
  lightness: 0.17933988408185542
  saturation: 0.6442647255025804
  rhythmicContrast: 0.19014359591528773
purpose: []
