name: toga
favicon: null
layout_spectrum: 0.73525
typography_spectrum: 0.4813
title: toga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#466f90'
    - '#000000'
    - '#008080'
    - '#000080'
    - '#0000ff'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
